#!/bin/sh

# Read the commit message from the commit message file
COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat $COMMIT_MSG_FILE)
echo "$COMMIT_MSG" 
# Define the regex pattern to match the commit message format
PATTERN="^(feat|fix|test|chore):.*$"

# Check if the commit message matches the pattern
if ! echo "$COMMIT_MSG" | grep -iqE "$PATTERN"; then
  echo "Aborting commit: Your commit message does not follow the Conventional Commits format."
  echo "Allowed types: 'feat', 'fix', 'test', 'chore'."
  echo "Example commit message: 'feat: add new feature'"
  exit 1
fi

# If the commit message matches the pattern, allow the commit
exit 0
